### ISSUE TITLE
issue with qb-input

### ISSUE THREAD

**Issue by Knvctedd** [Re2team/qb-vault#1]
![image](https://user-images.githubusercontent.com/76920136/141783194-315e50c8-d917-4707-a010-cd56dcf39c5a.png)

**Comment by SubwooferNL** [comment]
i have the same with my input its not working

**Comment by Pitzo** [comment]
You need to use the updated version of qb-input.

**Comment by Hkarimi561** [comment]
@Knvctedd @SubwooferNL you need to update your qb-input 
you can download it from 
https://github.com/qbcore-framework/qb-input
it has some update for password text 
check it if the problem exist say to me or say to close the issues
one other thing is use the update version of qb-vault
